<a href="https://colab.research.google.com/github/satish24011993/mlops_project/blob/master/Pandas_Training_Notebook_BrowseJobs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🐼 Pandas for Data Engineering — Instructor Training Notebook
**BrowseJobs Technologies · Complete Course Companion**

Pandas is the **data-cleaning framework** of Python. Before any analysis, reporting or prediction model, the data must be cleaned — and pandas is how we do it.

This notebook is organised into **14 chapters** and is **fully runnable end to end**. Chapter 4 generates its own sample datasets, so nothing depends on files being pre-uploaded to `/content/`.

Each chapter has:
- **Concept** — a short explanation you can teach from
- **Runnable code** — press `Shift + Enter` and see real output
- **🧪 Class Practice** — exercises for students
- **💬 Interview Corner** — what actually gets asked in L1/L2 rounds

> ⚙️ **Run the SETUP cells in Chapter 4 first** — they create the CSV/JSON files used by the rest of the notebook.

## 📚 Table of Contents
1. Why Pandas — the four data problems
2. Series — a single column
3. DataFrame — rows and columns
4. Reading Data (⚙️ SETUP — run first!) · head · tail · info · describe
5. loc vs iloc
6. Cleaning 1 — Duplicate Data
7. Cleaning 2 — Missing Data (dropna · fillna · mean/median/mode)
8. Cleaning 3 — Wrong Data Types & Wrong Data
9. Data Validation Framework
10. Filtering & Creating New Columns
11. Merging DataFrames — the Joins
12. Reshaping — pivot & json_normalize
13. File Formats — CSV · JSON · Parquet · Avro · ORC, chunking & merging files
14. End-to-End Project — Finance ETL & Medallion Architecture

---
# Chapter 1 · Why Pandas — The Four Data Problems

**Pandas is a framework used to clean data.** Raw data arriving from a business is almost never usable as-is. There are four problems we fix, every single time:

| # | Problem | Example |
|---|---|---|
| 1 | **Missing data** | salary is `null`, city is `unknown` |
| 2 | **Duplicate data** | the same customer row appears three times |
| 3 | **Wrong data type** | salary stored as `'180000'` (a string) instead of a number |
| 4 | **Wrong data** | `city = 'male'`, a phone number sitting in the salary column |

### Look at this raw table — every row has a problem
```
customername | age | salary       | city
a            | 16  | null         | unknown      ← missing data
b            | 18  | 150000       | bangalore    ← clean
c            | 21  | 180000       | chennai      ← clean
e            | 25  | 180000       | bangalore
e            | 25  | '180000'     | bangalore    ← duplicate + wrong TYPE (string)
e            | 25  | 6363402444   | male         ← wrong data in BOTH columns
```
If you group this by city to report total sales, your numbers are **wrong** — that is why cleaning comes first.

**Why we clean:** data analysis / reporting · prediction modelling. Garbage in → garbage dashboards.

### Array vs List (the vocabulary question)
- **Array** — *homogeneous*: every element the same type.
- **List** — *heterogeneous*: can hold any mix of types.

In [ ]:
# List: heterogeneous — any mix of types
x = [1, 2, 'a', True]
print(x)

# Array-like: homogeneous — all the same type
y = [1, 2, 3, 4, 5]
print(y)

---
# Chapter 2 · Series — a Single Column

A **Series** is like **one column in a table** — a one-dimensional labelled array.

In [2]:
import pandas as pd

a = [1, 7, 2]
myvar = pd.Series(a)
print(myvar)
# Notice the automatic index: 0, 1, 2

0    1
1    7
2    2
dtype: int64

In [ ]:
# Access by position
myvar[2]

np.int64(2)

In [ ]:
# Give it custom labels with index=
myvar = pd.Series(a, index=['x', 'y', 'z'])
print(myvar)

x    1
y    7
z    2
dtype: int64

In [ ]:
# Now access by LABEL
myvar['y']

np.int64(7)

### 🧪 Class Practice 2
1. Create a Series of five marks with student names as the index.
2. Fetch the mark of the third student two ways — by position and by label.

In [ ]:
# ✏️ Try it here

---
# Chapter 3 · DataFrame — Rows and Columns

A **DataFrame** is **two-dimensional** — rows *and* columns. It is a whole table. The most common way to build one by hand is from a dictionary, where **each key becomes a column**.

In [ ]:
import pandas as pd

data = {
    "calories": [420, 10, 100, 50],
    "duration": [50, 5, 50, 65]
}

df = pd.DataFrame(data)
print(df)

   calories  duration
0       420        50
1        10         5
2       100        50
3        50        65

In [ ]:
# A DataFrame is really a collection of Series — one per column
print(type(df))
print(type(df['calories']))

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>

### 🧪 Class Practice 3
Build a DataFrame of five employees with columns `name`, `age`, `city`, `salary`. Print it, then print just the `salary` column.

In [ ]:
# ✏️ Try it here

---
# Chapter 4 · ⚙️ SETUP + Reading Data

Real data comes from files. Run the next cell **once** — it generates the sample files this notebook uses (a deliberately *messy* fitness CSV and a JSON file), so nothing needs to be uploaded.

In [ ]:
# ⚙️ SETUP — generate the sample data files
# (In your projects this data would arrive as a real CSV from the business.)
import pandas as pd
import numpy as np

np.random.seed(42)

sample = {
    'Duration': [60, 60, 60, 45, 45, 60, 60, 60, 45, 60, 60, 60, 60, 60, 60,
                 60, 60, 45, 60, 45, 60, 60, 60, 450, 30, 60, 60, 60, 60, 60],
    'Date': ['2020/12/01','2020/12/02','2020/12/03','2020/12/04','2020/12/05',
             '2020/12/06','2020/12/07','2020/12/08','2020/12/09','2020/12/10',
             '2020/12/11','2020/12/12','2020/12/12','2020/12/13','2020/12/14',
             '2020/12/15','2020/12/16','2020/12/17','2020/12/18','2020/12/19',
             '2020/12/20','2020/12/21', np.nan ,'2020/12/23','2020/12/24',
             '2020/12/25','20201226','2020/12/27','2020/12/28','2020/12/29'],
    'Pulse': [110,117,103,109,117,102,110,104,109,98,103,100,100,106,104,
              98,98,100,90,103,97,108,100,130,102,105,100,92,103,100],
    'Maxpulse': [130,145,135,175,148,127,136,134,133,124,147,120,120,128,132,
                 123,120,120,112,123,125,131,119,101,126,132,118,115,132,132],
    'Calories': [409.1,479.0,340.0,282.4,406.0,300.0,374.0,253.3,195.1,269.0,
                 329.3,250.7,250.7,345.3,379.3,275.0,215.2,300.0, np.nan ,323.0,
                 243.0,364.2,282.0,300.0,334.5,353.2,np.nan,243.0,np.nan,280.0]
}
pd.DataFrame(sample).to_csv('data.csv', index=False)

# a small JSON file too
pd.DataFrame({'x':[10,8,13,9], 'y':[8.04,6.95,7.58,8.81], 'series':['I','I','I','I']}).to_json(
    'sample.json', orient='records')

print('✅ Created data.csv (30 rows, with duplicates, nulls and bad values) and sample.json')

✅ Created data.csv (30 rows, with duplicates, nulls and bad values) and sample.json

In [ ]:
# Read a CSV into a DataFrame
import pandas as pd
df = pd.read_csv('data.csv')
df

    Duration        Date  Pulse  Maxpulse  Calories
0         60  2020/12/01    110       130     409.1
1         60  2020/12/02    117       145     479.0
2         60  2020/12/03    103       135     340.0
3         45  2020/12/04    109       175     282.4
4         45  2020/12/05    117       148     406.0
5         60  2020/12/06    102       127     300.0
6         60  2020/12/07    110       136     374.0
7         60  2020/12/08    104       134     253.3
8         45  2020/12/09    109       133     195.1
9         60  2020/12/10     98       124     269.0
10        60  2020/12/11    103       147     329.3
11        60  2020/12/12    100       120     250.7
12        60  2020/12/12    100       120     250.7
13        60  2020/12/13    106       128     345.3
14        60  2020/12/14    104       132     379.3
15        60  2020/12/15     98       123     275.0
16        60  2020/12/16     98       120     215.2
17        45  2020/12/17    100       120     300.0
18        60  2020/12/18     90       112       NaN
19        45  2020/12/19    103       123     323.0
20        60  2020/12/20     97       125     243.0
21        60  2020/12/21    108       131     364.2
22        60         NaN    100       119     282.0
23       450  2020/12/23    130       101     300.0
24        30  2020/12/24    102       126     334.5
25        60  2020/12/25    105       132     353.2
26        60    20201226    100       118       NaN
27        60  2020/12/27     92       115     243.0
28        60  2020/12/28    103       132       NaN
29        60  2020/12/29    100       132     280.0

In [ ]:
# head() — the top sample. Use it to confirm you got the RIGHT data
# and to understand the schema before doing anything else.
df.head()        # top 5 rows by default

   Duration        Date  Pulse  Maxpulse  Calories
0        60  2020/12/01    110       130     409.1
1        60  2020/12/02    117       145     479.0
2        60  2020/12/03    103       135     340.0
3        45  2020/12/04    109       175     282.4
4        45  2020/12/05    117       148     406.0

In [ ]:
df.tail(10)      # bottom 10 rows

    Duration        Date  Pulse  Maxpulse  Calories
20        60  2020/12/20     97       125     243.0
21        60  2020/12/21    108       131     364.2
22        60         NaN    100       119     282.0
23       450  2020/12/23    130       101     300.0
24        30  2020/12/24    102       126     334.5
25        60  2020/12/25    105       132     353.2
26        60    20201226    100       118       NaN
27        60  2020/12/27     92       115     243.0
28        60  2020/12/28    103       132       NaN
29        60  2020/12/29    100       132     280.0

In [ ]:
# info() — the single most useful command in pandas.
# Row count · column names · non-null counts · data types · memory
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  30 non-null     int64
 1   Date      29 non-null     object
 2   Pulse     30 non-null     int64
 3   Maxpulse  30 non-null     int64
 4   Calories  27 non-null     float64
dtypes: float64(1), int64(3), object(1)
memory usage: 1.3+ KB

In [ ]:
# describe() — quick statistics on the numeric columns
df.describe()

         Duration       Pulse    Maxpulse    Calories
count   30.000000   30.000000   30.000000   27.000000
mean    69.500000  103.933333  128.766667  310.233333
std     72.258516    7.794487   13.343430   65.531325
min     30.000000   90.000000  101.000000  195.100000
25%     60.000000  100.000000  120.000000  261.150000
50%     60.000000  103.000000  127.500000  300.000000
75%     60.000000  107.500000  132.750000  349.250000
max    450.000000  130.000000  175.000000  479.000000

In [ ]:
# Reading JSON — JavaScript Object Notation, the most common format
# for systems to exchange data between themselves.
jdf = pd.read_json('sample.json')
jdf

    x     y series
0  10  8.04      I
1   8  6.95      I
2  13  7.58      I
3   9  8.81      I

### 💬 Interview Corner
**"What is the first thing you do after loading a dataset?"**
→ `df.head()` to confirm it's the right data, then `df.info()` to check row count, data types and nulls. That single pair of commands drives the entire cleaning plan.

### 🧪 Class Practice 4
1. How many rows and columns does `df` have?
2. Which columns contain nulls, and how many? (hint: read the `info()` output)
3. What is the mean `Calories`? Use `describe()`.

In [ ]:
# ✏️ Try it here

---
# Chapter 5 · loc vs iloc ⭐

The classic beginner interview question.

| | `loc` | `iloc` |
|---|---|---|
| Selects by | **Label** (row/column names) | **Integer position** |
| Example | `df.loc[0, 'Duration']` | `df.iloc[1, 1]` |
| Slice end | **Inclusive** | **Exclusive** |

Memory hook: **l**oc = **l**abel · **i**loc = **i**nteger.

In [ ]:
df

    Duration        Date  Pulse  Maxpulse  Calories
0         60  2020/12/01    110       130     409.1
1         60  2020/12/02    117       145     479.0
2         60  2020/12/03    103       135     340.0
3         45  2020/12/04    109       175     282.4
4         45  2020/12/05    117       148     406.0
5         60  2020/12/06    102       127     300.0
6         60  2020/12/07    110       136     374.0
7         60  2020/12/08    104       134     253.3
8         45  2020/12/09    109       133     195.1
9         60  2020/12/10     98       124     269.0
10        60  2020/12/11    103       147     329.3
11        60  2020/12/12    100       120     250.7
12        60  2020/12/12    100       120     250.7
13        60  2020/12/13    106       128     345.3
14        60  2020/12/14    104       132     379.3
15        60  2020/12/15     98       123     275.0
16        60  2020/12/16     98       120     215.2
17        45  2020/12/17    100       120     300.0
18        60  2020/12/18     90       112       NaN
19        45  2020/12/19    103       123     323.0
20        60  2020/12/20     97       125     243.0
21        60  2020/12/21    108       131     364.2
22        60         NaN    100       119     282.0
23       450  2020/12/23    130       101     300.0
24        30  2020/12/24    102       126     334.5
25        60  2020/12/25    105       132     353.2
26        60    20201226    100       118       NaN
27        60  2020/12/27     92       115     243.0
28        60  2020/12/28    103       132       NaN
29        60  2020/12/29    100       132     280.0

In [ ]:
# loc — use the NAME of the column
df.loc[1, 'Pulse']

np.int64(117)

In [ ]:
# iloc — only integer positions for BOTH row and column
df.iloc[1, 1]

'2020/12/02'

In [ ]:
# Slicing: loc is inclusive of the end, iloc is exclusive
print(df.loc[0:2, 'Duration'])     # rows 0,1,2  ← 3 rows
print()
print(df.iloc[0:2, 2])             # rows 0,1    ← 2 rows

0    60
1    60
2    60
Name: Duration, dtype: int64

0    110
1    117
Name: Pulse, dtype: int64

In [ ]:
# Whole rows and column ranges
df.loc[3, ['Duration', 'Pulse', 'Calories']]

Duration       45
Pulse         109
Calories    282.4
Name: 3, dtype: object

### 🧪 Class Practice 5
1. Get the `Pulse` of row 5 using both `loc` and `iloc`.
2. Get rows 10–15 with only the `Date` and `Calories` columns.
3. Explain out loud why `df.loc[0:2]` returns three rows but `df.iloc[0:2]` returns two.

In [ ]:
# ✏️ Try it here

---
# Chapter 6 · Cleaning 1 — Duplicate Data

Duplicates inflate every total in your dashboard. Find them, then drop them.

⚠️ **The `inplace` trap:** `df.drop_duplicates()` returns a *new* DataFrame and leaves `df` untouched. Either assign the result or pass `inplace=True`.

In [ ]:
df = pd.read_csv('data.csv')
print('rows before:', len(df))

# Find them first
print('duplicate rows:', df.duplicated().sum())
df[df.duplicated(keep=False)]      # show every copy

rows before: 30
duplicate rows: 1

    Duration        Date  Pulse  Maxpulse  Calories
11        60  2020/12/12    100       120     250.7
12        60  2020/12/12    100       120     250.7

In [ ]:
# ❌ This does NOT change df — a classic mistake
df.drop_duplicates()
print('still:', len(df))

# ✅ Either of these works
newdf = df.drop_duplicates()       # assign the result
df.drop_duplicates(inplace=True)   # or modify in place
print('after:', len(df))

still: 30
after: 29

In [ ]:
# Drop duplicates based on SPECIFIC columns only
df2 = pd.read_csv('data.csv')
df2.drop_duplicates(subset=['Duration', 'Pulse'], keep='first').head()

### 🧪 Class Practice 6
1. Reload `data.csv` and count duplicates two ways: `df.duplicated().sum()` and comparing `len()` before/after.
2. Use `keep='last'` instead of `'first'` — which row survives?

In [ ]:
# ✏️ Try it here

---
# Chapter 7 · Cleaning 2 — Missing Data

Two strategies:

| Strategy | Command | When to use |
|---|---|---|
| **Delete** the rows | `dropna()` | Few nulls, plenty of data |
| **Fill** the gaps | `fillna(value)` | Deleting would lose too much |

### What do we fill WITH?
1. A **fixed value** — `fillna(130)`
2. A value **provided by the business** — ask, don't guess
3. A **statistic**: **mean** (average) · **median** (middle value) · **mode** (most frequent)

**The BrowseJobs rule of thumb:** numeric → mean or median · date → a sentinel like `01/01/1900` · string → `'unknown'`.

In [ ]:
df = pd.read_csv('data.csv')

# Count nulls per column — do this BEFORE deciding anything
df.isnull().sum()

In [ ]:
# --- Strategy 1: DELETE the null rows ---
newdf = df.dropna()
print('original:', len(df), ' after dropna:', len(newdf))
newdf.info()

In [ ]:
# --- Strategy 2a: fill EVERYTHING with a fixed value ---
df = pd.read_csv('data.csv')
newdf = df.fillna(130)
newdf.isnull().sum()

In [ ]:
# --- Strategy 2b: fill ONE column only (much more common) ---
df = pd.read_csv('data.csv')
df['Calories'] = df['Calories'].fillna(130)
df.isnull().sum()

In [ ]:
# --- Strategy 2c: mean / median / mode ---
df = pd.read_csv('data.csv')

x = df['Calories'].mean()      # average
y = df['Pulse'].median()       # middle value
z = df['Duration'].mode()[0]   # most frequent — mode() returns a Series, take [0]!

print('mean Calories:', round(x, 2), '| median Pulse:', y, '| mode Duration:', z)

df['Calories'] = df['Calories'].fillna(x)
df.isnull().sum()

### ⚠️ Two traps students always hit
1. **`mode()` returns a Series**, not a single value — you must index it: `df['col'].mode()[0]`. Passing the Series straight into `fillna()` silently does nothing useful.
2. **`inplace=True` on a column slice is deprecated** in modern pandas. Prefer the assignment form:
   `df['col'] = df['col'].fillna(x)` instead of `df['col'].fillna(x, inplace=True)`.

### 💬 Interview Corner — mean vs median
Use the **median** when the column has outliers (one salary of ₹5 crore drags the mean up but barely moves the median). Use the **mode** for categorical columns.

### 🧪 Class Practice 7
1. Fill `Calories` with the **median** instead of the mean — compare the two results.
2. Fill `Date` nulls with `'1900/01/01'`.
3. Which approach loses more information on this dataset: `dropna()` or `fillna()`? Justify with row counts.

In [ ]:
# ✏️ Try it here

---
# Chapter 8 · Cleaning 3 — Wrong Data Types & Wrong Data

### Wrong data type
A date stored as a string can't be sorted, filtered by month, or used in a time series. Fix it with `pd.to_datetime()`.

### Wrong data
Data that is *valid* as a type but *impossible* in reality — a 450-minute workout, a negative salary, `city = 'male'`. Two options: **correct it** to a boundary value, or **delete** the row.

In [ ]:
import pandas as pd
df = pd.read_csv('data.csv')
df.info()      # look at Dtype: Date is 'object' = a string!

In [ ]:
# Convert to a real datetime.
# errors='coerce' turns anything unparseable into NaT instead of crashing.
df['Date'] = pd.to_datetime(df['Date'], errors='coerce', format='mixed')
df.info()      # Date is now datetime64

In [ ]:
# Now fill the resulting missing dates with the business sentinel
df['Date'] = df['Date'].fillna(pd.Timestamp('1900-01-01'))
df.head(3)

In [ ]:
# Reformat the display: dd-mm-yyyy
df['Date_display'] = df['Date'].dt.strftime('%d-%m-%Y')
df[['Date', 'Date_display']].head()

In [ ]:
# --- WRONG DATA: fix out-of-range values ---
# Row 23 has a Duration of 450 minutes — nobody works out for 7.5 hours.
print('before:', df['Duration'].max())

for i in df.index:
    if df.loc[i, 'Duration'] > 120:
        df.loc[i, 'Duration'] = 120        # cap it at a sensible boundary

print('after :', df['Duration'].max())

In [ ]:
# The vectorised version — faster and more 'pandas-native' than looping
df2 = pd.read_csv('data.csv')
df2.loc[df2['Duration'] > 120, 'Duration'] = 120
print(df2['Duration'].max())

In [ ]:
# Or DELETE the bad rows entirely
df3 = pd.read_csv('data.csv')
df3 = df3[df3['Duration'] <= 120]
print('rows kept:', len(df3))

### 🧪 Class Practice 8
1. Convert `Date` to datetime and count how many became `NaT` (the badly-formatted `20201226` row).
2. Cap `Pulse` at 125 using the vectorised form.
3. Which is better for a production pipeline — capping or deleting? Discuss when each is right.

In [ ]:
# ✏️ Try it here

---
# Chapter 9 · Data Validation Framework

Validation runs **before** transformation (is the file even usable?) and **after** transformation (did we break anything?). This checklist is what separates a data engineer from someone who "knows pandas".

| # | Validation | What you check |
|---|---|---|
| 1 | **Naming convention** | `finance_01012026.csv` — not `f.csv` |
| 2 | **File type** | Is it actually a CSV, not an Excel file renamed? |
| 3 | **File size** | A 0 KB or suspiciously small file = upstream failure |
| 4 | **Row count** | Actual vs expected number of rows |
| 5 | **Schema** | Expected columns vs actual columns |
| 6 | **Data type** | Expected dtypes vs actual dtypes |
| 7 | **Missing data** | Count of nulls per column |
| 8 | **Wrong data** | Values outside the expected range/domain |
| 9 | **Duplicates** | Count of duplicate rows |

In [ ]:
import pandas as pd, os

def validate(path, expected_cols, expected_min_rows=1):
    """A minimal validation harness you can drop into any pipeline."""
    report = {}
    report['file_exists']  = os.path.exists(path)
    report['file_size_kb'] = round(os.path.getsize(path) / 1024, 2)

    df = pd.read_csv(path)
    report['row_count']       = len(df)
    report['row_count_ok']    = len(df) >= expected_min_rows
    report['schema_ok']       = list(df.columns) == expected_cols
    report['missing_columns'] = set(expected_cols) - set(df.columns)
    report['null_counts']     = df.isnull().sum().to_dict()
    report['duplicate_rows']  = int(df.duplicated().sum())
    report['dtypes']          = df.dtypes.astype(str).to_dict()
    return report

for k, v in validate('data.csv',
                     ['Duration','Date','Pulse','Maxpulse','Calories'],
                     expected_min_rows=25).items():
    print(f'{k:18} : {v}')

### 🧪 Class Practice 9
1. Add a **wrong-data check** to `validate()`: flag any `Duration > 120`.
2. Make the function raise an exception if `schema_ok` is `False` — pipelines should fail loudly, not silently.

In [ ]:
# ✏️ Try it here

---
# Chapter 10 · Filtering & Creating New Columns

### The filtering syntax trap ⚠️
When combining conditions you must use:
- `&` for AND, `|` for OR (**not** `and` / `or`)
- **Round brackets around every condition** — `&` binds tighter than `>`

```python
df[(df['age'] > 30) & (df['city'] == 'bangalore')]     # ✅
df[df['age'] > 30 & df['city'] == 'bangalore']         # ❌ error
```

In [ ]:
import pandas as pd
df = pd.read_csv('data.csv')

# Single condition
df[df['Calories'] > 350].head()

In [ ]:
# Two conditions with & — note the brackets around EACH one
df[(df['Calories'] > 300) & (df['Pulse'] < 105)].head()

In [ ]:
# OR with |
df[(df['Duration'] == 45) | (df['Pulse'] > 120)].head()

In [ ]:
# isin() — the pandas equivalent of SQL's IN
df[df['Duration'].isin([30, 45])].head()

In [ ]:
# Creating new columns — plain arithmetic across columns
df['intensity']    = df['Calories'] / df['Duration']
df['pulse_reserve'] = df['Maxpulse'] - df['Pulse']
df[['Duration','Calories','intensity','pulse_reserve']].head()

In [ ]:
# Conditional column — the pandas version of a SQL CASE statement
import numpy as np
df['effort'] = np.where(df['Calories'] > 350, 'high',
               np.where(df['Calories'] > 250, 'medium', 'low'))
df[['Calories','effort']].head(8)

In [ ]:
# Grouping — the pandas equivalent of SQL GROUP BY
df.groupby('Duration').agg(
    sessions=('Calories', 'count'),
    avg_calories=('Calories', 'mean'),
    max_pulse=('Maxpulse', 'max')
).reset_index()

### 🧪 Class Practice 10
1. All rows where `Maxpulse` is above 130 **and** `Duration` is 60.
2. A new column `calories_per_beat` = Calories ÷ Maxpulse.
3. Group by your `effort` column and count the sessions in each band.

In [ ]:
# ✏️ Try it here

---
# Chapter 11 · Merging DataFrames — the Joins

`pd.merge()` is the pandas version of a SQL JOIN. The `how=` parameter picks the type.

| `how=` | Result |
|---|---|
| `'inner'` | Only **matching** rows from both |
| `'left'` | All from the **left** + matches from the right (nulls where no match) |
| `'right'` | All from the **right** + matches from the left |
| `'outer'` | **Everything** from both tables |
| `'cross'` | Cartesian product — every row × every row |

In [ ]:
import pandas as pd

df1 = pd.DataFrame({'id': [1, 2, 3, 4], 'Name': ['krish', 'ajay', 'adveer', 'anuj']})
df2 = pd.DataFrame({'id': [3, 4, 5], 'age': [25, 28, 22]})
print(df1); print(); print(df2)

   id    Name
0   1   krish
1   2    ajay
2   3  adveer
3   4    anuj

   id  age
0   3   25
1   4   28
2   5   22

In [ ]:
# INNER — only ids 3 and 4 exist in both
pd.merge(df1, df2, on='id', how='inner')

   id    Name  age
0   3  adveer   25
1   4    anuj   28

In [ ]:
# LEFT — all four names; ages are NaN where there's no match
pd.merge(df1, df2, on='id', how='left')

   id    Name   age
0   1   krish   NaN
1   2    ajay   NaN
2   3  adveer  25.0
3   4    anuj  28.0

In [ ]:
# RIGHT — all three ages; id 5 has no name
pd.merge(df1, df2, on='id', how='right')

   id    Name  age
0   3  adveer   25
1   4    anuj   28
2   5     NaN   22

In [ ]:
# OUTER (full outer join) — everything from both
pd.merge(df1, df2, on='id', how='outer')

   id    Name   age
0   1   krish   NaN
1   2    ajay   NaN
2   3  adveer  25.0
3   4    anuj  28.0
4   5     NaN  22.0

In [ ]:
# When the key columns have DIFFERENT names, use left_on / right_on
customers = pd.DataFrame({'id': [1, 2, 3], 'name': ['a', 'b', 'c']})
orders    = pd.DataFrame({'customerid': [1, 1, 3], 'amount': [100, 250, 90]})

pd.merge(customers, orders, left_on='id', right_on='customerid', how='left')

In [ ]:
# Merging on MULTIPLE keys — pass a list
a = pd.DataFrame({'city':['bangalore','ajmer','kolkata','delhi'],
                  'id':[1,2,3,4], 'Name':['krish','ajay','adveer','anuj']})
b = pd.DataFrame({'city':['kolkata','ajmer','bangalore','delhi'],
                  'id':[3,4,1,2], 'age':[25,28,22,24]})

print(pd.merge(a, b, on=['id'], how='inner'))          # city_x / city_y suffixes appear
print()
print(pd.merge(a, b, on=['id','city'], how='inner'))   # matches BOTH keys — fewer rows

In [ ]:
# Chaining THREE tables: merge two, then merge the result with the third
t1 = pd.DataFrame({'id':[1,2,3], 'Name':['john','Anna','Peter']})
t2 = pd.DataFrame({'id':[3,4,5], 'age':[25,28,22]})
t3 = pd.DataFrame({'id':[1,2,3], 'country':['USA','UK','India']})

output = pd.merge(t1, t2, on='id', how='inner')
newdf  = pd.merge(output, t3, on='id', how='inner')
newdf

   id   Name  age country
0   3  Peter   25   India

In [ ]:
# concat — STACK dataframes instead of joining them (rows on top of rows)
pd.concat([t1, pd.DataFrame({'id':[9], 'Name':['zara']})], ignore_index=True)

   id   Name
0   1   john
1   2   Anna
2   3  Peter
3   9   zara

### 💬 Interview Corner — merge vs concat vs join
- **`merge`** — combine on **key columns** (SQL JOIN).
- **`concat`** — **stack** dataframes vertically (or side by side with `axis=1`); no key needed.
- **`join`** — merges on the **index** by default; a convenience wrapper around merge.

### 🧪 Class Practice 11
1. Run all four `how=` values on `df1`/`df2` and write down the row count of each. Explain the pattern.
2. Merge `customers` and `orders`, then group by customer name to get total amount per customer.
3. Recreate this dry-run on the whiteboard, then verify in code:
```
table1: 1,1,2,3,4,null,null,2,5      table2: 1,2,4,null,2,3,4,null,7
inner: 1,1,2,2,2,2,3,4,4
left : inner + null,null,5
right: inner + null,null,7
outer: inner + null,null,5,null,null,7
```

In [ ]:
# ✏️ Try it here

---
# Chapter 12 · Reshaping — pivot & json_normalize

### pivot — turn rows into columns
Long format (one row per date-city) → wide format (dates as rows, cities as columns).

### json_normalize — flatten nested JSON
APIs return nested JSON. `json_normalize` flattens `address.city` into a proper column.

In [ ]:
import pandas as pd

df = pd.DataFrame({
    'date': ['2021-01-01', '2021-01-01', '2021-01-02', '2021-01-02'],
    'city': ['newyork', 'los angeles', 'newyork', 'los angeles'],
    'temperature': [32, 75, 34, 77]})
df

         date         city  temperature
0  2021-01-01      newyork           32
1  2021-01-01  los angeles           75
2  2021-01-02      newyork           34
3  2021-01-02  los angeles           77

In [ ]:
# index = the rows | columns = what becomes column headers | values = the cells
newdf = df.pivot(index='date', columns='city', values='temperature')
newdf

city        los angeles  newyork
date
2021-01-01           75       32
2021-01-02           77       34

In [ ]:
# Pivot MULTIPLE value columns at once → a multi-level column header
data = {
    'Date': ['2023-01-01','2023-01-01','2023-01-02','2023-01-02'],
    'City': ['New York','Los Angeles','New York','Los Angeles'],
    'Temperature': [32, 75, 34, 77],
    'Humidity': [80, 60, 70, 65],
    'Wind Speed': [10, 15, 12, 14]
}
df = pd.DataFrame(data)
df

         Date         City  Temperature  Humidity  Wind Speed
0  2023-01-01     New York           32        80          10
1  2023-01-01  Los Angeles           75        60          15
2  2023-01-02     New York           34        70          12
3  2023-01-02  Los Angeles           77        65          14

In [ ]:
newdf = df.pivot(index='Date', columns='City', values=['Temperature','Humidity','Wind Speed'])
print(newdf)

           Temperature             Humidity           Wind Speed
City       Los Angeles New York Los Angeles New York Los Angeles New York
Date
2023-01-01          75       32          60       80          15       10
2023-01-02          77       34          65       70          14       12

In [ ]:
# pivot_table — like pivot but AGGREGATES duplicates instead of erroring
df.pivot_table(index='City', values=['Temperature','Humidity'], aggfunc='mean')

In [ ]:
# --- json_normalize: flatten a nested dictionary ---
data1 = {
    'id': 123,
    'name': 'krish',
    'address': {
        'street': '123 main st',
        'city': 'bangalore',
        'state': 'karnataka'
    }
}
df = pd.json_normalize(data1)
print(df)
print()
print('columns →', list(df.columns))   # address.street, address.city, address.state

In [3]:
# A LIST of nested records — the shape an API actually returns
data = [
    {"id": 1, "name": "Alice",
     "location": {"city": "New York", "state": "NY"},
     "skills": ["Python", "SQL"]},
    {"id": 2, "name": "Bob",
     "location": {"city": "San Francisco", "state": "CA"},
     "skills": ["Java", "AWS"]}
]
pd.json_normalize(data)

   id   name         skills  location.city location.state
0   1  Alice  [Python, SQL]       New York             NY
1   2    Bob    [Java, AWS]  San Francisco             CA

In [4]:
# explode() — turn the list in 'skills' into one row per skill
pd.json_normalize(data).explode('skills').reset_index(drop=True)

   id   name  skills  location.city location.state
0   1  Alice  Python       New York             NY
1   1  Alice     SQL       New York             NY
2   2    Bob    Java  San Francisco             CA
3   2    Bob     AWS  San Francisco             CA

### 🧪 Class Practice 12
1. Pivot the fitness data: `Duration` as rows, and mean `Calories` as values (use `pivot_table`).
2. Normalize this order JSON and name the resulting columns:
```python
{'orderid':'1', 'customer':{'customerid':'123','name':'krish','address':'bangalore'}}
```

In [ ]:
# ✏️ Try it here

---
# Chapter 13 · File Formats & Working With Large Files

| Format | Structure | Storage | Notes |
|---|---|---|---|
| **CSV** | Structured | Row | Human readable, no types, no compression |
| **Excel** (xlsx/xlsb/xlsm) | Structured | Row | Sheets, formatting |
| **JSON** | Semi-structured | — | Nested; how systems exchange data |
| **Parquet** | Structured | **Columnar** | Compressed, binary, read-heavy → analytics |
| **Avro** | Structured | **Row** | Compressed (snappy), write-heavy → streaming |
| **ORC** | Structured | **Columnar** | Compressed, read-heavy → analytics |
| **Word / PDF** | Unstructured | — | Needs parsing before use |

### Why Parquet dominates big data
- **Columnar storage** → faster to locate and scan just the columns you need
- **Compressed** → far less disk space
- **Parallelism** → supports parallel processing
- **Schema evolution** → handles added/removed columns automatically
- **Metadata included** — column names, types, schema (data about data)
- **Binary** → humans can't read it directly (that's the trade-off)

### How data reaches you
- **Email / SFTP ingestion** → download and move the file to a central folder
- **JDBC connection** → url · username · password · port · database · table
- **API** → url · authentication · query string (filters), via the `requests` library

In [ ]:
import pandas as pd

df = pd.DataFrame({
    'name': ['alice', 'bob', 'charlie'],
    'age': [25, 30, 35],
    'city': ['newyork', 'sanfrancisco', 'losangeles']
})

df.to_parquet('data.parquet')       # write
newdf = pd.read_parquet('data.parquet')   # read back
newdf

      name  age          city
0    alice   25       newyork
1      bob   30  sanfrancisco
2  charlie   35    losangeles

In [7]:
# Compare the sizes — parquet compression on a bigger frame
import numpy as np, os
big = pd.DataFrame({'id': range(50000),
                    'city': np.random.choice(['bangalore','chennai','delhi'], 50000),
                    'amount': np.random.randint(100, 9999, 50000)})
big.to_csv('big.csv', index=False)
big.to_parquet('big.parquet')

print('csv     :', round(os.path.getsize('big.csv')/1024, 1), 'KB')
print('parquet :', round(os.path.getsize('big.parquet')/1024, 1), 'KB')

csv     : 912.8 KB
parquet : 430.2 KB

### Large files — process in CHUNKS
A 10 GB CSV won't fit in memory. `chunksize` streams it: 1,000,000 rows ÷ 100,000 = 10 chunks processed one at a time.

In [8]:
# Chunked processing: transform and append, writing the header only once
chunk = 10000
first_chunk = True

for part in pd.read_csv('big.csv', chunksize=chunk):
    part['uppercity'] = part['city'].str.upper()        # the transformation
    part.to_csv('newdata.csv', mode='a', index=False, header=first_chunk)
    first_chunk = False                                  # header only on the first write

print('rows written:', len(pd.read_csv('newdata.csv')))

rows written: 50000

In [9]:
df = pd.read_csv('newdata.csv')
df

          id       city  amount  uppercity
0          0    chennai    2973    CHENNAI
1          1  bangalore    6168  BANGALORE
2          2    chennai    9399    CHENNAI
3          3  bangalore    6800  BANGALORE
4          4    chennai    7936    CHENNAI
...      ...        ...     ...        ...
49995  49995  bangalore    7629  BANGALORE
49996  49996      delhi    9700      DELHI
49997  49997  bangalore    4276  BANGALORE
49998  49998    chennai    9395    CHENNAI
49999  49999    chennai    9121    CHENNAI

[50000 rows x 4 columns]

In [10]:
# --- Merge many files into one ---
import glob, os
os.makedirs('csvfolder', exist_ok=True)
for i in range(3):                                        # create 3 sample files
    pd.DataFrame({'id':[i*2+1, i*2+2], 'city':['bangalore','chennai']}).to_csv(
        f'csvfolder/file{i}.csv', index=False)

# glob lists all files matching a pattern in a folder
files = glob.glob('csvfolder/*.csv')
print(files)


# List comprehension reads each file; concat stacks them.
# ignore_index=True resets the index on the new dataframe.
mergedf = pd.concat([pd.read_csv(f) for f in files], ignore_index=True)
mergedf = mergedf.drop_duplicates()
mergedf.dropna()
mergedf.to_csv('mergedf.csv')

['csvfolder/file1.csv', 'csvfolder/file0.csv', 'csvfolder/file2.csv']

In [11]:
# If the files have DIFFERENT columns, use sort=True so concat aligns them
dfs = []
for file in files:
    dfs.append(pd.read_csv(file))
mergedf = pd.concat(dfs, ignore_index=True, sort=True)
mergedf.head()

        city  id
0  bangalore   3
1    chennai   4
2  bangalore   1
3    chennai   2
4  bangalore   5

### 🧪 Class Practice 13
1. Write `mergedf` to parquet and compare the file size against the CSV.
2. Change `chunksize` to 5000 — how many chunks are processed?
3. In Colab you can mount Drive with `from google.colab import drive; drive.mount('/content/drive')` — try reading a CSV from your own Drive folder.

In [ ]:
# ✏️ Try it here

---
# Chapter 14 · End-to-End Project — Finance ETL

### The brief (a real requirement, written the way a business writes it)
> *A CSV lands in a folder every morning at 12 AM CST from the finance team. Read it into a DataFrame and transform it: remove duplicates; fill nulls with the mean if numeric, `01011900` if a date, `'unknown'` if a string; build the aggregated finance columns. Once cleaned, save the output in parquet format to another folder.*

### Medallion Architecture — how modern pipelines are layered
| Layer | Contents |
|---|---|
| 🥉 **Bronze** | **Raw** data exactly as received — never edited |
| 🥈 **Silver** | **Transformed** — duplicates dropped, nulls fixed, data types corrected |
| 🥇 **Gold** | **Aggregated** business columns — reporting reads from here |

### The finance formulas
| Column | Formula |
|---|---|
| Total revenue | `Revenue` |
| Total expense | `Expenses` |
| Profit | `Revenue − Expenses` |
| Gross margin | `(Revenue − COGS) / Revenue` |
| Operating income | `Revenue − Operating_Expenses` |
| EBITDA | `operating_income + Depreciation + Amortization` |
| Accounts receivable / payable | `AR` / `AP` |
| Year-over-year growth | `Revenue × 0.05` |

In [12]:
# 🥉 BRONZE — generate/receive the raw file
# (This block simulates the finance team's messy CSV. In production you'd
#  simply do: df = pd.read_csv('/path/finance_01012026.csv')
import pandas as pd
import numpy as np
np.random.seed(7)

n = 100
raw = {
    'Date': pd.date_range('2025-03-07', periods=n, freq='h'),
    'Revenue':            np.random.randint(1000, 5000, size=n).astype(float),
    'Expenses':           np.random.randint(500, 2000, size=n).astype(float),
    'COGS':               np.random.randint(300, 1500, size=n).astype(float),
    'Operating_Expenses': np.random.randint(200, 1000, size=n).astype(float),
    'Depreciation':       np.random.randint(50, 200, size=n),
    'Amortization':       np.random.randint(50, 200, size=n),
    'Cash_Inflows':       np.random.randint(1000, 3000, size=n),
    'Cash_Outflows':      np.random.randint(500, 2500, size=n),
    'AR':                 np.random.randint(100, 1500, size=n),
    'AP':                 np.random.randint(100, 1500, size=n),
}
dfi = pd.DataFrame(raw)

# inject 5 REAL duplicate rows (an exact copy of the first five)
dfi = pd.concat([dfi, dfi.head(5)], ignore_index=True)

# inject nulls into the numeric columns
null_rows = np.random.choice(dfi.index, size=15, replace=False)
for c in ['Revenue', 'Expenses', 'Operating_Expenses', 'COGS']:
    dfi.loc[null_rows, c] = np.nan

# a string column, with some nulls
dfi['Department'] = (['Sales', 'Marketing', 'Finance', 'HR', 'Legal'] * 21)[:len(dfi)]
dfi.loc[10:20, 'Department'] = np.nan

dfi.to_csv('finance_raw.csv', index=False)
print('🥉 Bronze written: finance_raw.csv —', len(dfi), 'rows')

🥉 Bronze written: finance_raw.csv — 105 rows

In [13]:
# --- EXTRACT: the actual starting point of the project ---
df = pd.read_csv('finance_raw.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 105 entries, 0 to 104
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Date                105 non-null    object
 1   Revenue             90 non-null     float64
 2   Expenses            90 non-null     float64
 3   COGS                90 non-null     float64
 4   Operating_Expenses  90 non-null     float64
 5   Depreciation        105 non-null    int64
 6   Amortization        105 non-null    int64
 7   Cash_Inflows        105 non-null    int64
 8   Cash_Outflows       105 non-null    int64
 9   AR                  105 non-null    int64
 10  AP                  105 non-null    int64
 11  Department          94 non-null     object
dtypes: float64(4), int64(6), object(2)
memory usage: 10.0+ KB

In [14]:
# 🥈 SILVER — transformation step 1: drop duplicates
print('rows before:', len(df))
df.drop_duplicates(inplace=True)
print('rows after :', len(df))

rows before: 105
rows after : 101

In [16]:
df['Date'] = df['Date'].fillna('01011900')
df['Department'] = df['Department'].fillna('unknown')

In [17]:
# 🥈 SILVER — step 2: fill nulls by column TYPE
# numeric → mean
for col in ['Revenue', 'Expenses', 'COGS', 'Operating_Expenses']:
    df[col] = df[col].fillna(df[col].mean())

# date → business sentinel
df['Date'] = df['Date'].fillna('01011900')

# string → 'unknown'
df['Department'] = df['Department'].fillna('unknown')

df.isnull().sum()
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 101 entries, 0 to 100
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Date                101 non-null    object
 1   Revenue             101 non-null    float64
 2   Expenses            101 non-null    float64
 3   COGS                101 non-null    float64
 4   Operating_Expenses  101 non-null    float64
 5   Depreciation        101 non-null    int64
 6   Amortization        101 non-null    int64
 7   Cash_Inflows        101 non-null    int64
 8   Cash_Outflows       101 non-null    int64
 9   AR                  101 non-null    int64
 10  AP                  101 non-null    int64
 11  Department          101 non-null    object
dtypes: float64(4), int64(6), object(2)
memory usage: 10.3+ KB

In [18]:
# 🥇 GOLD — build the aggregated reporting columns
df['total_revenue']         = df['Revenue']
df['total_expense']         = df['Expenses']
df['profit']                = df['Revenue'] - df['Expenses']
df['gross_margin']          = (df['Revenue'] - df['COGS']) / df['Revenue']
df['operating_income']      = df['Revenue'] - df['Operating_Expenses']
df['EBITDA']                = df['operating_income'] + df['Depreciation'] + df['Amortization']
df['accounts_receivables']  = df['AR']
df['accounts_payables']     = df['AP']
df['year_over_year_growth'] = df['Revenue'] * 0.05

df[['total_revenue','profit','gross_margin','operating_income','EBITDA']].head()

   total_revenue       profit  gross_margin  operating_income       EBITDA
0    2982.930233  1882.023256      0.716351       2370.837209  2640.837209
1    2220.000000  1318.000000      0.360811       1814.000000  2071.000000
2    1537.000000  1016.000000      0.685751       1147.000000  1391.000000
3    3550.000000  2847.000000      0.850704       2964.000000  3165.000000
4    2603.000000  2056.000000      0.533615       1854.000000  2072.000000

In [19]:
# --- LOAD: save the gold layer in parquet (and csv for inspection) ---
df.to_parquet('finance_gold.parquet')
df.to_csv('finance_gold.csv', index=False)

# post-load validation — always read it back and confirm
check = pd.read_parquet('finance_gold.parquet')
print('rows :', len(check))
print('cols :', len(check.columns))
print('nulls:', check.isnull().sum().sum())
check.head(3)

rows : 101
cols : 21
nulls: 0

,Date,Revenue,Expenses,COGS,Operating_Expenses,Depreciation,Amortization,Cash_Inflows,Cash_Outflows,AR,...,Department,total_revenue,total_expense,profit,gross_margin,operating_income,EBITDA,accounts_receivables,accounts_payables,year_over_year_growth
0,2025-03-07 00:00:00,2982.930233,1100.906977,846.104651,612.093023,84,186,2365,758,1163,...,Sales,2982.930233,1100.906977,1882.023256,0.716351,2370.837209,2640.837209,1163,1016,149.146512
1,2025-03-07 01:00:00,2220.000000,902.000000,1419.000000,406.000000,130,127,2814,1186,535,...,Marketing,2220.000000,902.000000,1318.000000,0.360811,1814.000000,2071.000000,535,116,111.000000
2,2025-03-07 02:00:00,1537.000000,521.000000,483.000000,390.000000,91,153,1329,991,853,...,Finance,1537.000000,521.000000,1016.000000,0.685751,1147.000000,1391.000000,853,755,76.850000

In [20]:
# A quick business summary — what the dashboard would show
df.groupby('Department').agg(
    total_revenue=('total_revenue', 'sum'),
    total_profit=('profit', 'sum'),
    avg_gross_margin=('gross_margin', 'mean')
).round(2)

            total_revenue  total_profit  avg_gross_margin
Department
Finance          56213.86      34994.05              0.69
HR               56178.72      38231.09              0.69
Legal            50224.79      32764.07              0.64
Marketing        53138.93      31032.02              0.67
Sales            53312.86      33627.05              0.69
unknown          32206.79      19436.07              0.63

### 💬 Interview Corner — describe this project in an L2 round (STAR)
- **Situation:** the finance team drops a daily CSV at 12 AM CST with duplicates, nulls and inconsistent dates.
- **Task:** build a reliable daily pipeline producing reporting-ready finance metrics.
- **Action:** extract → validate (row count, schema, dtypes) → Silver transformations (drop duplicates, type-aware null filling, dtype fixes) → Gold aggregations (profit, gross margin, operating income, EBITDA, YoY growth) → write to parquet in the output folder.
- **Result:** a compressed, columnar, reporting-ready dataset the analytics team reads directly, with validation counts logged at every stage.

### 🧪 Final Class Practice
1. Add a **post-transformation validation** block asserting row count and zero nulls; make it raise if either fails.
2. Add a `profit_margin` column = `profit / Revenue` and a CASE-style `performance` band (`np.where`).
3. Re-run the whole pipeline with `chunksize` to prove it works on a file too big for memory.

In [ ]:
# ✏️ Try it here

---
# 🎓 Course Recap — One-Slide Summary

| Chapter | Key takeaway |
|---|---|
| 01 Why Pandas | 4 problems: missing · duplicate · wrong type · wrong data |
| 02 Series | One column, 1-D, custom index with `index=` |
| 03 DataFrame | 2-D table; build from a dict — each key becomes a column |
| 04 Reading | `read_csv` / `read_json` · `head` · `tail` · `info` · `describe` |
| 05 loc vs iloc | **l**oc = **l**abel (inclusive) · **i**loc = **i**nteger (exclusive) |
| 06 Duplicates | `duplicated()` to find · `drop_duplicates(inplace=True)` to fix |
| 07 Missing data | `dropna()` deletes · `fillna()` fills · mean/median/mode — `mode()[0]`! |
| 08 Types & bad data | `pd.to_datetime(errors='coerce')` · `.dt.strftime()` · cap or delete outliers |
| 09 Validation | naming · type · size · rows · schema · dtypes · nulls · wrong · duplicates |
| 10 Filter/new cols | `&` `\|` with brackets · `isin()` · `np.where` = CASE · `groupby().agg()` |
| 11 Merge | `how=` inner/left/right/outer/cross · `left_on`/`right_on` · concat stacks |
| 12 Reshape | `pivot(index, columns, values)` · `pivot_table` aggregates · `json_normalize` |
| 13 File formats | Parquet: columnar, compressed, binary, read-heavy · chunksize · glob + concat |
| 14 Project | Bronze raw → Silver clean → Gold aggregated → parquet out |

*Built for BrowseJobs Technologies · Pandas Training Track*